#/bin/bash
export TARGET_URL='FQDN'
export TARGET_PORT=80
export NUM_THREADS=
export NUM_ITERATIONS=
export TOR=TRUE
export SLEEP_TIMER=
export USER_AGENT_PAYLOAD='CUSTOM USER AGENT'
python slapshot_get.py
unset TARGET_URL
unset TARGET_PORT
unset NUM_THREADS
unset NUM_ITERATIONS
unset TOR
unset SLEEP_TIMER
unset USER_AGENT_PAYLOAD
